### ISSUE TITLE
readme needs rewriting?

### ISSUE THREAD

**Issue by vcvpaiva** [own-pt/own-pt#5]
subject says it all. this readme might be the one for own-en.

**Comment by arademaker** [comment]
I tried to improve. Please reopen if you have more specific changes in mind.

**Comment by vcvpaiva** [comment]
much better, many thanks! small thing "experiment branch of http://openwordnet-pt.org" ==> experimental branch of xxx or this branch is an experiment based on http://openwordnet-pt.org
